#!/usr/bin/env node
import { execFileSync } from 'child_process'
import fs from 'fs'
import { createRequire } from 'module'
import path from 'path'
import protobuf from 'protobufjs'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const moduleRoot = path.resolve(__dirname, '..')

// nanopb generator must match the vendored runtime in cpp/nanopb.
const NANOPB_VERSION = '0.4.9.1'

// Signature stamped onto every file this generator emits (nitrogen/margelo style).
function signedHeader(filename, p = '//') {
  return [
    p,
    `${p} ${filename}`,
    `${p} This file was generated by react-native-nitro-protobuf. DO NOT MODIFY THIS FILE.`,
    `${p} https://github.com/KlaappInc/react-native-nitro-protobuf`,
    `${p} Copyright © Thomas Roux @ Klaapp (https://klaapp.io)`,
    p,
  ].join('\n')
}

function findExecutable(name) {
  const exts =
    process.platform === 'win32' ? ['.exe', '.cmd', '.bat', ''] : ['']
  for (const dir of (process.env.PATH ?? '').split(path.delimiter)) {
    for (const ext of exts) {
      const candidate = path.join(dir, name + ext)
      if (fs.existsSync(candidate)) return candidate
    }
  }
  return null
}

function venvBinDir(venv) {
  return path.join(venv, process.platform === 'win32' ? 'Scripts' : 'bin')
}

// protoc: explicit flag/env -> grpc-tools bundle -> system protoc.
function resolveProtoc(args) {
  if (args.protoc) return args.protoc
  if (process.env.PROTOC) return process.env.PROTOC
  try {
    const require = createRequire(import.meta.url)
    const pkg = require.resolve('grpc-tools/package.json')
    const bin = path.join(
      path.dirname(pkg),
      'bin',
      process.platform === 'win32' ? 'protoc.exe' : 'protoc'
    )
    if (fs.existsSync(bin)) return bin
  } catch {
    // grpc-tools not installed; fall through to system protoc.
  }
  const system = findExecutable('protoc')
  if (system) return system
  throw new Error(
    'protoc not found. Reinstall dependencies (grpc-tools provides a bundled ' +
      'protoc) or pass --protoc <path>.'
  )
}

// nanopb plugin: explicit flag/env -> cached venv -> bootstrap (python3 + pip).
function resolveNanopbPlugin(args) {
  if (args.nanopb) return args.nanopb
  if (process.env.NANOPB_PLUGIN) return process.env.NANOPB_PLUGIN
  if (process.env.NANOPB_PROTOC_GEN) return process.env.NANOPB_PROTOC_GEN

  const cacheDir = path.join(moduleRoot, '.cache')
  const venv = path.join(cacheDir, 'nanopb-venv')
  const pluginName =
    process.platform === 'win32' ? 'protoc-gen-nanopb.exe' : 'protoc-gen-nanopb'
  const plugin = path.join(venvBinDir(venv), pluginName)
  if (fs.existsSync(plugin)) return plugin

  const python = findExecutable('python3') ?? findExecutable('python')
  if (!python) {
    throw new Error(
      'The nanopb code generator is missing and python3 (needed once to install ' +
        'it) was not found. Install python3, or install nanopb yourself and pass ' +
        '--nanopb <path to protoc-gen-nanopb>.'
    )
  }

  console.error(
    `[nitro-protobuf] Installing nanopb ${NANOPB_VERSION} generator (one-time setup)…`
  )
  fs.mkdirSync(cacheDir, { recursive: true })
  execFileSync(python, ['-m', 'venv', venv], { stdio: 'inherit' })
  const pip = path.join(
    venvBinDir(venv),
    process.platform === 'win32' ? 'pip.exe' : 'pip'
  )
  execFileSync(pip, ['install', '--quiet', `nanopb==${NANOPB_VERSION}`], {
    stdio: 'inherit',
  })
  if (!fs.existsSync(plugin)) {
    throw new Error(
      'nanopb bootstrap failed: protoc-gen-nanopb not found after install.'
    )
  }
  return plugin
}

// The grpc-tools-bundled protoc ships the well-known-type protos under
// <grpc-tools>/bin/google/protobuf/*.proto. Returns that include root (the dir
// that contains `google/`) so `import "google/protobuf/timestamp.proto"` works.
function wktIncludeDir() {
  try {
    const require = createRequire(import.meta.url)
    const pkg = require.resolve('grpc-tools/package.json')
    const dir = path.join(path.dirname(pkg), 'bin')
    if (
      fs.existsSync(path.join(dir, 'google', 'protobuf', 'timestamp.proto'))
    ) {
      return dir
    }
  } catch {
    // grpc-tools unavailable; WKT imports must be resolvable another way.
  }
  return null
}

// Scan the given .proto files for `import "google/protobuf/X.proto"` and return
// the absolute paths of the imported WKT files (so nanopb also generates them).
function collectWktImports(protoFiles, wktDir) {
  const found = new Set()
  if (!wktDir) return []
  for (const file of protoFiles) {
    let text = ''
    try {
      text = fs.readFileSync(file, 'utf8')
    } catch {
      continue
    }
    for (const m of text.matchAll(
      /import\s+(?:public\s+)?"(google\/protobuf\/[^"]+)"/g
    )) {
      const abs = path.join(wktDir, m[1])
      if (fs.existsSync(abs)) found.add(abs)
    }
  }
  return [...found]
}

function usage() {
  return [
    'Usage: react-native-nitro-protobuf <command> [options]',
    '',
    'Commands:',
    '  init                   Scaffold proto/, config, and a generate script',
    '  generate               Generate nanopb sources, registry, and TS types (default)',
    '',
    'Options:',
    '  --protoDir <path>      Directory containing .proto files (default: ./proto)',
    '  --outDir <path>        Output directory for generated C/registry (default: <module>/generated)',
    '  --tsOut <path>         Output directory for generated TS types (default: outDir)',
    '  --protoPath <path>     Extra import paths for protoc (repeatable)',
    '  --protoc <path>        Path to protoc binary (default: bundled grpc-tools)',
    '  --nanopb <path>        Path to protoc-gen-nanopb (default: auto-installed)',
    '  --strict               Require explicit .options for every static field',
    '  --skipProtoc           Skip protoc invocation (registry only)',
    '  --watch, -w            Regenerate on .proto changes (debounced)',
    '  --bigint               Type 64-bit fields as bigint (default: decimal string)',
    '  --enums <mode>         Enum representation: "string" or "number" (default)',
    '  --help                 Show help',
    '',
    'Field size limits default to 256/256/16 (max_length/max_size/max_count).',
    'Override globally in nitro-protobuf.config.json or per-field in *.options.',
  ].join('\n')
}

function parseArgs(argv) {
  const args = { _: [], protoPath: [], skipProtoc: false }
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i]
    if (arg === '--protoDir') {
      args.protoDir = argv[++i]
    } else if (arg === '--outDir') {
      args.outDir = argv[++i]
    } else if (arg === '--tsOut') {
      args.tsOut = argv[++i]
    } else if (arg === '--protoPath') {
      args.protoPath.push(argv[++i])
    } else if (arg === '--protoc') {
      args.protoc = argv[++i]
    } else if (arg === '--nanopb' || arg === '--nanopbPlugin') {
      args.nanopb = argv[++i]
    } else if (arg === '--skipProtoc' || arg === '--skip-protoc') {
      args.skipProtoc = true
    } else if (arg === '--strict') {
      args.strict = true
    } else if (arg === '--watch' || arg === '-w') {
      args.watch = true
    } else if (arg === '--bigint') {
      args.bigint = true
    } else if (arg === '--enums') {
      args.enums = argv[++i] // 'string' | 'number'
    } else if (arg === '--help' || arg === '-h') {
      args.help = true
    } else {
      args._.push(arg)
    }
  }
  return args
}

function collectProtoFiles(dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true })
  const files = []
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      files.push(...collectProtoFiles(fullPath))
    } else if (entry.isFile() && entry.name.endsWith('.proto')) {
      files.push(fullPath)
    }
  }
  return files
}

function cppString(value) {
  // Escape backslashes first, then double quotes, for a C++ string literal.
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

function mapFieldType(field) {
  if (field.resolvedType instanceof protobuf.Type) return 'Message'
  if (field.resolvedType instanceof protobuf.Enum) return 'Enum'
  switch (field.type) {
    case 'bool':
      return 'Bool'
    case 'int32':
      return 'Int32'
    case 'int64':
      return 'Int64'
    case 'uint32':
      return 'UInt32'
    case 'uint64':
      return 'UInt64'
    case 'sint32':
      return 'SInt32'
    case 'sint64':
      return 'SInt64'
    case 'fixed32':
      return 'Fixed32'
    case 'fixed64':
      return 'Fixed64'
    case 'sfixed32':
      return 'SFixed32'
    case 'sfixed64':
      return 'SFixed64'
    case 'float':
      return 'Float'
    case 'double':
      return 'Double'
    case 'string':
      return 'String'
    case 'bytes':
      return 'Bytes'
    default:
      throw new Error(`Unsupported field type: ${field.type}`)
  }
}

// "my_map" -> "MyMap" (protoc/nanopb name the synthetic map entry
// "<Message>_<PascalField>Entry").
function pascalCase(name) {
  return name
    .split('_')
    .filter(Boolean)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('')
}

// proto map key type -> codec FieldType (keys are scalar/string only).
const MAP_KEY_FIELD_TYPE = {
  int32: 'Int32',
  sint32: 'SInt32',
  sfixed32: 'SFixed32',
  uint32: 'UInt32',
  fixed32: 'Fixed32',
  int64: 'Int64',
  sint64: 'SInt64',
  sfixed64: 'SFixed64',
  uint64: 'UInt64',
  fixed64: 'Fixed64',
  bool: 'Bool',
  string: 'String',
}

// Parse all *.options files in the given dirs into a Map of
// target-pattern -> Set(optionKeys present). nanopb targets may use `*` globs.
function loadOptionsKeys(dirs) {
  const map = new Map()
  const seen = new Set()
  for (const dir of dirs) {
    let entries = []
    try {
      entries = fs.readdirSync(dir)
    } catch {
      continue
    }
    for (const name of entries) {
      if (!name.endsWith('.options')) continue
      const full = path.join(dir, name)
      if (seen.has(full)) continue
      seen.add(full)
      const text = fs.readFileSync(full, 'utf8')
      for (const raw of text.split('\n')) {
        const line = raw.replace(/#.*$/, '').trim()
        if (!line) continue
        const m = line.match(/^(\S+)\s+(.*)$/)
        if (!m) continue
        const target = m[1]
        const keys = [...m[2].matchAll(/([A-Za-z_]+)\s*:/g)].map((x) => x[1])
        if (!map.has(target)) map.set(target, new Set())
        for (const k of keys) map.get(target).add(k)
      }
    }
  }
  return map
}

function optionPatternMatches(pattern, name) {
  const rx = new RegExp(
    '^' +
      pattern
        .split('*')
        .map((s) => s.replace(/[.+?^${}()|[\]\\]/g, '\\$&'))
        .join('.*') +
      '$'
  )
  return rx.test(name)
}

function fieldHasOption(optsMap, fullField, key) {
  for (const [pattern, keys] of optsMap) {
    if (keys.has(key) && optionPatternMatches(pattern, fullField)) return true
  }
  return false
}

// Hard-fail if any codec-supported static field is missing the nanopb option
// that keeps it a static (non-callback) field. oneof/map fields are skipped:
// the codec rejects them at runtime regardless, so they never become static.
function validateOptions(messages, optsMap) {
  const problems = []
  for (const message of messages) {
    const fullName = message.fullName.startsWith('.')
      ? message.fullName.slice(1)
      : message.fullName
    for (const field of message.fieldsArray) {
      if (field.partOf || field.map) continue
      const ff = `${fullName}.${field.name}`
      if (field.repeated && !fieldHasOption(optsMap, ff, 'max_count')) {
        problems.push(`${ff} (repeated) needs 'max_count'`)
      }
      if (
        field.type === 'string' &&
        !fieldHasOption(optsMap, ff, 'max_length')
      ) {
        problems.push(`${ff} (string) needs 'max_length'`)
      }
      if (field.type === 'bytes' && !fieldHasOption(optsMap, ff, 'max_size')) {
        problems.push(`${ff} (bytes) needs 'max_size'`)
      }
    }
  }
  if (problems.length > 0) {
    throw new Error(
      'Missing required nanopb .options for static fields (else nanopb emits ' +
        'callback fields the codec cannot handle at runtime):\n  - ' +
        problems.join('\n  - ') +
        '\nAdd them to a .options file beside your .proto, e.g.\n' +
        '  acme.User.name max_length: 64'
    )
  }
}

// Non-strict mode: warn (don't fail) about static fields that fall back to the
// synthesized default limits, so a payload silently over the default is easy to
// spot. Skips oneof/map (handled separately) and well-known-type fields.
function warnDefaultLimits(messages, optsMap, defaults) {
  const onDefault = []
  for (const message of messages) {
    const fullName = cleanName(message.fullName)
    if (fullName.startsWith('google.protobuf.')) continue
    for (const field of message.fieldsArray) {
      if (field.partOf || field.map) continue
      const ff = `${fullName}.${field.name}`
      if (field.repeated && !fieldHasOption(optsMap, ff, 'max_count')) {
        onDefault.push(`${ff} (repeated, max_count: ${defaults.maxCount})`)
      }
      if (
        field.type === 'string' &&
        !fieldHasOption(optsMap, ff, 'max_length')
      ) {
        onDefault.push(`${ff} (string, max_length: ${defaults.maxLength})`)
      }
      if (field.type === 'bytes' && !fieldHasOption(optsMap, ff, 'max_size')) {
        onDefault.push(`${ff} (bytes, max_size: ${defaults.maxSize})`)
      }
    }
  }
  if (onDefault.length === 0) return
  const shown = onDefault.slice(0, 8)
  console.error(
    `[nitro-protobuf] ${onDefault.length} field(s) use default size limits; ` +
      `values exceeding them throw at encode. Tune via a .options file:\n  - ` +
      shown.join('\n  - ') +
      (onDefault.length > shown.length
        ? `\n  - …and ${onDefault.length - shown.length} more`
        : '')
  )
}

// Built-in default field limits (override via config / inline .options).
const DEFAULT_LIMITS = { maxLength: 256, maxSize: 256, maxCount: 16 }

// Load nitro-protobuf.config.json (or a `nitroProtobuf` key in package.json)
// from the working directory. All fields optional.
function loadConfig(cwd) {
  const jsonPath = path.join(cwd, 'nitro-protobuf.config.json')
  if (fs.existsSync(jsonPath)) {
    try {
      return JSON.parse(fs.readFileSync(jsonPath, 'utf8'))
    } catch (e) {
      throw new Error(`Invalid nitro-protobuf.config.json: ${e.message}`)
    }
  }
  const pkgPath = path.join(cwd, 'package.json')
  if (fs.existsSync(pkgPath)) {
    try {
      return JSON.parse(fs.readFileSync(pkgPath, 'utf8')).nitroProtobuf ?? {}
    } catch {
      return {}
    }
  }
  return {}
}

// nanopb reads the FIRST `<proto>.options` found in ['.'] + options_path. We
// synthesize, in a temp dir searched first, a merged file per proto:
// wildcard defaults (so every static field is sized without hand-written
// options) followed by the user's own .options (specific entries override the
// `*` defaults). Returns the temp dir to pass via `--nanopb_opt=-I`.
function writeMergedOptions(
  protoFiles,
  includeDirs,
  defaults,
  outDir,
  wktImports = [],
  wktDir = null
) {
  const tempDir = path.join(outDir, '.nanopb-options')
  fs.rmSync(tempDir, { recursive: true, force: true })
  fs.mkdirSync(tempDir, { recursive: true })
  const header =
    `# Auto-generated defaults (nitro-protobuf). Specific entries below win.\n` +
    `* max_length: ${defaults.maxLength}\n` +
    `* max_size: ${defaults.maxSize}\n` +
    `* max_count: ${defaults.maxCount}\n`
  for (const proto of protoFiles) {
    const base = path.basename(proto, '.proto')
    let userOptions = ''
    for (const dir of includeDirs) {
      const candidate = path.join(dir, `${base}.options`)
      if (fs.existsSync(candidate)) {
        userOptions = fs.readFileSync(candidate, 'utf8')
        break
      }
    }
    fs.writeFileSync(
      path.join(tempDir, `${base}.options`),
      header +
        (userOptions
          ? `\n# User overrides (${base}.options)\n${userOptions}`
          : '')
    )
  }
  // Well-known types need the wildcard defaults too (e.g. FieldMask.paths is a
  // repeated string -> static array). nanopb keys options off the import path,
  // so write them at the matching relative path (google/protobuf/<name>.options).
  for (const wkt of wktImports) {
    const rel = (
      wktDir ? path.relative(wktDir, wkt) : path.basename(wkt)
    ).replace(/\.proto$/, '.options')
    const target = path.join(tempDir, rel)
    fs.mkdirSync(path.dirname(target), { recursive: true })
    fs.writeFileSync(target, header)
  }
  return tempDir
}

// "my_field" -> "myField" (proto3 JSON uses lowerCamelCase field names).
function lowerCamelCase(name) {
  return name.replace(/_([a-z])/g, (_, c) => c.toUpperCase())
}

// "acme.User" -> "AcmeUser"; "acme.Foo.Bar" -> "AcmeFooBar".
function tsTypeName(fullName) {
  const clean = fullName.startsWith('.') ? fullName.slice(1) : fullName
  return clean
    .split(/[._]/)
    .filter(Boolean)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('')
}

const WKT_TIMESTAMP = 'google.protobuf.Timestamp'
const WKT_DURATION = 'google.protobuf.Duration'
const cleanName = (fullName) =>
  fullName.startsWith('.') ? fullName.slice(1) : fullName

const I64_TYPES = new Set(['int64', 'uint64', 'sint64', 'fixed64', 'sfixed64'])

// Map a proto field to the codec's JS representation. Well-known Timestamp /
// Duration get a natural JS mapping (Date|string / number-of-ms). With
// opts.bigint, 64-bit fields are typed `bigint`; with opts.enumsAsStrings,
// enums are typed as their value-name string-literal union.
function tsFieldType(field, opts = {}) {
  let base
  if (field.resolvedType instanceof protobuf.Type) {
    const fn = cleanName(field.resolvedType.fullName)
    if (fn === WKT_TIMESTAMP) base = 'Date | string'
    else if (fn === WKT_DURATION) base = 'number'
    else base = tsTypeName(field.resolvedType.fullName)
  } else if (field.resolvedType instanceof protobuf.Enum) {
    base = opts.enumsAsStrings
      ? Object.keys(field.resolvedType.values)
          .map((n) => `'${n}'`)
          .join(' | ')
      : 'number'
  } else if (I64_TYPES.has(field.type)) {
    base = opts.bigint ? 'bigint' : 'string' // precision-safe by default
  } else {
    switch (field.type) {
      case 'bool':
        base = 'boolean'
        break
      case 'string':
        base = 'string'
        break
      case 'bytes':
        base = 'string | number[]' // base64 string or byte array
        break
      default:
        base = 'number'
    }
  }
  // map<K,V> -> a JS object keyed by string (or number for integer keys).
  if (field.map) {
    const keyTs =
      field.keyType === 'string' || field.keyType === 'bool'
        ? 'string'
        : 'number'
    return `{ [key: ${keyTs}]: ${base} }`
  }
  return field.repeated ? `(${base})[]` : base
}

// Per-message TS interfaces + typed `Message.encode/decode` objects + a generic
// facade. Timestamp/Duration fields are converted to/from Date|ISO / ms via a
// spec-driven recursive transform.
function generateTypes(messages, opts = {}) {
  const out = [signedHeader('nitro-protobuf.ts'), '']
  out.push(
    'import {',
    '  NitroProtobuf,',
    '  classifyProtobufError,',
    "} from '@klaappinc/react-native-nitro-protobuf'",
    ''
  )

  const byName = new Map(messages.map((m) => [cleanName(m.fullName), m]))
  // Enums referenced by a field, collected for the string<->number maps.
  const enums = new Map() // fullName -> { name->id }
  const enumKey = (en) => cleanName(en.fullName).replace(/\./g, '_')
  // The conversion kind of a field's VALUE type (ignoring map/repeated):
  //   ts/dur (WKT), i64 (bigint), e:<EnumKey> (enum strings), <message name>.
  const baseKind = (field) => {
    if (field.resolvedType instanceof protobuf.Enum) {
      if (!opts.enumsAsStrings) return null
      enums.set(field.resolvedType.fullName, field.resolvedType.values)
      return `e:${enumKey(field.resolvedType)}`
    }
    if (field.resolvedType instanceof protobuf.Type) {
      const fn = cleanName(field.resolvedType.fullName)
      if (fn === WKT_TIMESTAMP) return 'ts'
      if (fn === WKT_DURATION) return 'dur'
      return fn // nested message name
    }
    if (opts.bigint && I64_TYPES.has(field.type)) return 'i64'
    return null
  }
  const isScalarConv = (k) =>
    k === 'ts' || k === 'dur' || k === 'i64' || (k && k.startsWith('e:'))
  const convCache = new Map()
  const needsConv = (name, stack = new Set()) => {
    if (convCache.has(name)) return convCache.get(name)
    if (stack.has(name)) return false
    stack.add(name)
    const m = byName.get(name)
    let res = false
    if (m) {
      for (const f of m.fieldsArray) {
        const bk = baseKind(f) // map/repeated share the value's conversion
        if (isScalarConv(bk)) {
          res = true
          break
        }
        if (bk && byName.has(bk) && needsConv(bk, stack)) {
          res = true
          break
        }
      }
    }
    convCache.set(name, res)
    return res
  }
  // Spec kind actually stored for a field: scalar inline, m:<kind> for a map
  // whose values need conversion, or a nested-message name.
  const fieldKind = (field) => {
    const bk = baseKind(field)
    if (bk == null) return null
    if (field.map) {
      if (isScalarConv(bk)) return `m:${bk}`
      return byName.has(bk) && needsConv(bk) ? `m:${bk}` : null
    }
    return bk
  }
  // A kind applied inline by the runtime (not a bare nested-message name).
  const isScalarKind = (k) => isScalarConv(k) || (k && k.startsWith('m:'))
  const specFor = (name) => {
    const m = byName.get(name)
    const spec = {}
    if (!m) return spec
    for (const f of m.fieldsArray) {
      const k = fieldKind(f)
      if (isScalarKind(k)) spec[f.name] = k
      else if (k && byName.has(k) && needsConv(k)) spec[f.name] = k
    }
    return spec
  }

  for (const m of messages) {
    out.push(`export interface ${tsTypeName(m.fullName)} {`)
    for (const f of m.fieldsArray) {
      out.push(`  ${f.name}?: ${tsFieldType(f, opts)}`)
    }
    out.push('}', '')
  }

  out.push('export interface NitroProtobufMessages {')
  for (const m of messages) {
    out.push(`  '${cleanName(m.fullName)}': ${tsTypeName(m.fullName)}`)
  }
  out.push('}', '')
  out.push(
    'export type NitroProtobufMessageName = keyof NitroProtobufMessages',
    ''
  )

  const conv = {}
  for (const m of messages) {
    const s = specFor(cleanName(m.fullName))
    if (Object.keys(s).length) conv[cleanName(m.fullName)] = s
  }

  // Canonical proto3-JSON metadata: per field [propName, jsonName, kind] where
  // kind drives value formatting (r:/m: prefixes for repeated/map). Collects
  // enum maps too (JSON uses enum value names regardless of the --enums option).
  const jsonKind = (field) => {
    let base = ''
    if (field.resolvedType instanceof protobuf.Enum) {
      enums.set(field.resolvedType.fullName, field.resolvedType.values)
      base = `e:${enumKey(field.resolvedType)}`
    } else if (field.resolvedType instanceof protobuf.Type) {
      const fn = cleanName(field.resolvedType.fullName)
      if (fn === WKT_TIMESTAMP) base = 'ts'
      else if (fn === WKT_DURATION) base = 'dur'
      else base = byName.has(fn) ? fn : '' // unsupported WKT -> passthrough
    } else if (I64_TYPES.has(field.type)) {
      base = 'i64'
    } else if (field.type === 'bytes') {
      base = 'by'
    }
    if (field.map) return `m:${base}`
    if (field.repeated) return `r:${base}`
    return base
  }
  const jsonMeta = {}
  for (const m of messages) {
    jsonMeta[cleanName(m.fullName)] = m.fieldsArray.map((f) => [
      f.name,
      lowerCamelCase(f.name),
      jsonKind(f),
    ])
  }

  const enumMaps = {}
  for (const [fullName, values] of enums) {
    const d = {}
    for (const [n, id] of Object.entries(values)) d[id] = n
    enumMaps[enumKey({ fullName })] = { e: values, d }
  }

  out.push(
    `const _conv: Record<string, Record<string, string>> = ${JSON.stringify(conv)}`,
    `const _enums: Record<string, { e: Record<string, number>; d: Record<string, string> }> = ${JSON.stringify(enumMaps)}`,
    'function _toTimestamp(v: Date | string | number) {',
    '  const ms = v instanceof Date ? v.getTime() : typeof v === "number" ? v : Date.parse(v)',
    '  return { seconds: String(Math.trunc(ms / 1000)), nanos: Math.trunc((ms % 1000) * 1e6) }',
    '}',
    'function _fromTimestamp(t: any): string {',
    '  const ms = Number(t?.seconds ?? 0) * 1000 + Math.trunc(Number(t?.nanos ?? 0) / 1e6)',
    '  return new Date(ms).toISOString()',
    '}',
    'function _toDuration(ms: number) {',
    '  return { seconds: String(Math.trunc(ms / 1000)), nanos: Math.trunc((ms % 1000) * 1e6) }',
    '}',
    'function _fromDuration(d: any): number {',
    '  return Number(d?.seconds ?? 0) * 1000 + Number(d?.nanos ?? 0) / 1e6',
    '}',
    'function _enc1(kind: string, v: any): any {',
    '  if (v == null) return v',
    '  if (kind === "ts") return _toTimestamp(v)',
    '  if (kind === "dur") return _toDuration(v)',
    '  if (kind === "i64") return String(v)',
    '  if (kind.slice(0, 2) === "e:") return _enums[kind.slice(2)].e[v] ?? v',
    '  if (kind.slice(0, 2) === "m:") {',
    '    const vk = kind.slice(2)',
    '    const o: any = {}',
    '    for (const k in v) o[k] = _enc1(vk, v[k])',
    '    return o',
    '  }',
    '  return _encodeShape(kind, v)',
    '}',
    'function _dec1(kind: string, v: any): any {',
    '  if (v == null) return v',
    '  if (kind === "ts") return _fromTimestamp(v)',
    '  if (kind === "dur") return _fromDuration(v)',
    '  if (kind === "i64") return BigInt(v)',
    '  if (kind.slice(0, 2) === "e:") return _enums[kind.slice(2)].d[v] ?? v',
    '  if (kind.slice(0, 2) === "m:") {',
    '    const vk = kind.slice(2)',
    '    const o: any = {}',
    '    for (const k in v) o[k] = _dec1(vk, v[k])',
    '    return o',
    '  }',
    '  return _decodeShape(kind, v)',
    '}',
    'function _encodeShape(name: string, m: any): any {',
    '  const spec = _conv[name]',
    '  if (!spec || m == null || typeof m !== "object") return m',
    '  const o: any = { ...m }',
    '  for (const f in spec) {',
    '    if (o[f] == null) continue',
    '    o[f] = Array.isArray(o[f]) ? o[f].map((x: any) => _enc1(spec[f], x)) : _enc1(spec[f], o[f])',
    '  }',
    '  return o',
    '}',
    'function _decodeShape(name: string, m: any): any {',
    '  const spec = _conv[name]',
    '  if (!spec || m == null || typeof m !== "object") return m',
    '  const o: any = { ...m }',
    '  for (const f in spec) {',
    '    if (o[f] == null) continue',
    '    o[f] = Array.isArray(o[f]) ? o[f].map((x: any) => _dec1(spec[f], x)) : _dec1(spec[f], o[f])',
    '  }',
    '  return o',
    '}',
    // Wrap native throws into typed ProtobufError subclasses.
    'function _enc(name: string, m: any): ArrayBuffer {',
    '  try {',
    '    return NitroProtobuf.encode(name, _encodeShape(name, m) as never)',
    '  } catch (e) {',
    '    throw classifyProtobufError(e, name)',
    '  }',
    '}',
    'function _dec(name: string, b: ArrayBuffer): any {',
    '  try {',
    '    return _decodeShape(name, NitroProtobuf.decode(name, b))',
    '  } catch (e) {',
    '    throw classifyProtobufError(e, name)',
    '  }',
    '}',
    'function _len(name: string, m: any): number {',
    '  try {',
    '    return NitroProtobuf.byteLength(name, _encodeShape(name, m) as never)',
    '  } catch (e) {',
    '    throw classifyProtobufError(e, name)',
    '  }',
    '}',
    ''
  )

  // Canonical proto3 JSON (camelCase keys, RFC3339 Timestamp, "Ns" Duration,
  // base64 bytes, enum names, 64-bit as strings). Distinct from the encode/decode
  // JS shape. Struct/Value/Any are not supported and are passed through as-is.
  out.push(
    `const _jf: Record<string, [string, string, string][]> = ${JSON.stringify(jsonMeta)}`,
    `const _bigint = ${opts.bigint}`,
    'const _B64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"',
    'function _bytesToB64(a: number[]): string {',
    '  let s = ""',
    '  for (let i = 0; i < a.length; i += 3) {',
    '    const t = (a[i] << 16) | ((a[i + 1] ?? 0) << 8) | (a[i + 2] ?? 0)',
    '    s += _B64[(t >> 18) & 63] + _B64[(t >> 12) & 63]',
    '    s += i + 1 < a.length ? _B64[(t >> 6) & 63] : "="',
    '    s += i + 2 < a.length ? _B64[t & 63] : "="',
    '  }',
    '  return s',
    '}',
    'function _toJsonVal(kind: string, v: any): any {',
    '  if (v == null) return v',
    '  if (kind.slice(0, 2) === "r:") return Array.isArray(v) ? v.map((x) => _toJsonVal(kind.slice(2), x)) : v',
    '  if (kind.slice(0, 2) === "m:") { const o: any = {}; for (const k in v) o[k] = _toJsonVal(kind.slice(2), v[k]); return o }',
    '  if (kind === "") return v',
    '  if (kind === "i64") return String(v)',
    '  if (kind === "by") return typeof v === "string" ? v : _bytesToB64(v)',
    '  if (kind === "ts") return v instanceof Date ? v.toISOString() : v',
    '  if (kind === "dur") return typeof v === "number" ? String(v / 1000) + "s" : v',
    '  if (kind.slice(0, 2) === "e:") return _enums[kind.slice(2)].d[v] ?? v',
    '  return _toJson(kind, v)',
    '}',
    'function _toJson(name: string, m: any): any {',
    '  const meta = _jf[name]',
    '  if (!meta || m == null || typeof m !== "object") return m',
    '  const o: any = {}',
    '  for (const [prop, jn, kind] of meta) {',
    '    if (m[prop] == null) continue',
    '    o[jn] = _toJsonVal(kind, m[prop])',
    '  }',
    '  return o',
    '}',
    'function _fromJsonVal(kind: string, v: any): any {',
    '  if (v == null) return v',
    '  if (kind.slice(0, 2) === "r:") return Array.isArray(v) ? v.map((x) => _fromJsonVal(kind.slice(2), x)) : v',
    '  if (kind.slice(0, 2) === "m:") { const o: any = {}; for (const k in v) o[k] = _fromJsonVal(kind.slice(2), v[k]); return o }',
    '  if (kind === "") return v',
    '  if (kind === "i64") return _bigint ? BigInt(v) : String(v)',
    '  if (kind === "by" || kind === "ts") return v',
    '  if (kind === "dur") return typeof v === "string" ? parseFloat(v) * 1000 : v',
    '  if (kind.slice(0, 2) === "e:") return typeof v === "number" ? v : (_enums[kind.slice(2)].e[v] ?? v)',
    '  return _fromJson(kind, v)',
    '}',
    'function _fromJson(name: string, j: any): any {',
    '  const meta = _jf[name]',
    '  if (!meta || j == null || typeof j !== "object") return j',
    '  const o: any = {}',
    '  for (const [prop, jn, kind] of meta) {',
    '    const val = j[jn] !== undefined ? j[jn] : j[prop]',
    '    if (val == null) continue',
    '    o[prop] = _fromJsonVal(kind, val)',
    '  }',
    '  return o',
    '}',
    ''
  )

  out.push(
    'export function encode<K extends NitroProtobufMessageName>(',
    '  name: K,',
    '  message: NitroProtobufMessages[K]',
    '): ArrayBuffer {',
    '  return _enc(name, message)',
    '}',
    '',
    'export function decode<K extends NitroProtobufMessageName>(',
    '  name: K,',
    '  data: ArrayBuffer',
    '): NitroProtobufMessages[K] {',
    '  return _dec(name, data) as NitroProtobufMessages[K]',
    '}',
    '',
    '/** Encoded byte length of a message without allocating the output buffer. */',
    'export function byteLength<K extends NitroProtobufMessageName>(',
    '  name: K,',
    '  message: NitroProtobufMessages[K]',
    '): number {',
    '  return _len(name, message)',
    '}',
    '',
    '/** Convert a message to canonical proto3 JSON (camelCase keys, etc.). */',
    'export function toJson<K extends NitroProtobufMessageName>(',
    '  name: K,',
    '  message: NitroProtobufMessages[K]',
    '): unknown {',
    '  return _toJson(name, message)',
    '}',
    '',
    '/** Parse canonical proto3 JSON into a message. */',
    'export function fromJson<K extends NitroProtobufMessageName>(',
    '  name: K,',
    '  json: unknown',
    '): NitroProtobufMessages[K] {',
    '  return _fromJson(name, json) as NitroProtobufMessages[K]',
    '}',
    ''
  )

  // Typed per-message objects (merge with the same-named interface): no magic
  // strings, full inference -> `AcmeUser.encode(u)` / `AcmeUser.decode(b)`.
  for (const m of messages) {
    const T = tsTypeName(m.fullName)
    const full = cleanName(m.fullName)
    // Field metadata for runtime reflection (name, tag, proto type, repeated).
    const fieldsMeta = m.fieldsArray.map((f) => {
      let type = f.type
      if (f.resolvedType) type = cleanName(f.resolvedType.fullName)
      return `{ name: '${f.name}', tag: ${f.id}, type: '${type}', repeated: ${!!f.repeated} }`
    })
    out.push(
      `export const ${T} = {`,
      `  messageName: '${full}' as const,`,
      `  encode: (m: ${T}): ArrayBuffer => _enc('${full}', m),`,
      `  decode: (b: ArrayBuffer): ${T} => _dec('${full}', b) as ${T},`,
      `  byteLength: (m: ${T}): number => _len('${full}', m),`,
      `  toJson: (m: ${T}): unknown => _toJson('${full}', m),`,
      `  fromJson: (j: unknown): ${T} => _fromJson('${full}', j) as ${T},`,
      `  fields: [${fieldsMeta.join(', ')}] as const,`,
      '}',
      ''
    )
  }
  return out.join('\n')
}

// Scaffold a new project: proto dir + sample .proto, config, and a
// proto:generate script in package.json.
function runInit(cwd) {
  const protoDir = path.join(cwd, 'proto')
  fs.mkdirSync(protoDir, { recursive: true })

  const sampleProto = path.join(protoDir, 'sample.proto')
  if (!fs.existsSync(sampleProto)) {
    fs.writeFileSync(
      sampleProto,
      [
        'syntax = "proto3";',
        'package app;',
        '',
        'message Profile {',
        '  uint32 id = 1;',
        '  string name = 2;',
        '  repeated string tags = 3;',
        '  bool active = 4;',
        '}',
        '',
      ].join('\n')
    )
    console.log('Created proto/sample.proto')
  }

  const configPath = path.join(cwd, 'nitro-protobuf.config.json')
  if (!fs.existsSync(configPath)) {
    fs.writeFileSync(
      configPath,
      JSON.stringify({ protoDir: 'proto', defaults: DEFAULT_LIMITS }, null, 2) +
        '\n'
    )
    console.log('Created nitro-protobuf.config.json')
  }

  const pkgPath = path.join(cwd, 'package.json')
  if (fs.existsSync(pkgPath)) {
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'))
    pkg.scripts = pkg.scripts ?? {}
    if (!pkg.scripts['proto:generate']) {
      pkg.scripts['proto:generate'] = 'react-native-nitro-protobuf generate'
      fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n')
      console.log('Added "proto:generate" script to package.json')
    }
  }

  console.log(
    '\nDone. Next:\n' +
      '  1. Edit proto/*.proto (limits default to 256/256/16; override in\n' +
      '     nitro-protobuf.config.json or per-field .options).\n' +
      '  2. Run: npm run proto:generate\n' +
      '  3. Rebuild your app (cd ios && pod install).\n' +
      "  4. import { encode, decode } from the generated 'nitro-protobuf' types.\n"
  )
}

async function runGenerate(args) {
  if (args._[0] === 'generate') {
    args._.shift()
  }

  const cwd = process.cwd()
  const config = loadConfig(cwd)
  const protoDir = path.resolve(
    cwd,
    args.protoDir ?? config.protoDir ?? 'proto'
  )
  const outDir = path.resolve(
    cwd,
    args.outDir ?? config.outDir ?? path.join(moduleRoot, 'generated')
  )
  const defaults = { ...DEFAULT_LIMITS, ...(config.defaults ?? {}) }
  const strict = args.strict ?? config.strict ?? false
  const tsOpts = {
    bigint: args.bigint ?? config.bigint ?? false,
    enumsAsStrings: (args.enums ?? config.enums) === 'string',
  }
  const wktDir = wktIncludeDir()
  const includeDirs = [
    protoDir,
    ...(args.protoPath ?? []).map((dir) => path.resolve(cwd, dir)),
    ...(wktDir ? [wktDir] : []), // google/protobuf/*.proto (well-known types)
  ]
  if (!fs.existsSync(protoDir)) {
    throw new Error(`Proto directory not found: ${protoDir}`)
  }

  const protoFiles = collectProtoFiles(protoDir).sort()
  if (protoFiles.length === 0) {
    throw new Error(`No .proto files found in ${protoDir}`)
  }
  // Imported well-known-type files must also be generated by nanopb.
  const wktImports = collectWktImports(protoFiles, wktDir)

  fs.mkdirSync(outDir, { recursive: true })

  if (!args.skipProtoc) {
    const protoc = resolveProtoc(args)
    const nanopbPlugin = resolveNanopbPlugin(args)

    const protocArgs = []
    includeDirs.forEach((dir) => protocArgs.push(`--proto_path=${dir}`))
    // In the default (non-strict) mode, synthesize wildcard default limits so
    // every static field is sized without hand-written .options. Searched first.
    if (!strict) {
      const optsDir = writeMergedOptions(
        protoFiles,
        includeDirs,
        defaults,
        outDir,
        wktImports,
        wktDir
      )
      protocArgs.push(`--nanopb_opt=-I${optsDir}`)
    }
    includeDirs.forEach((dir) => protocArgs.push(`--nanopb_opt=-I${dir}`))
    protocArgs.push(`--plugin=protoc-gen-nanopb=${nanopbPlugin}`)
    protocArgs.push(`--nanopb_out=${outDir}`)
    protocArgs.push(...protoFiles, ...wktImports)

    execFileSync(protoc, protocArgs, { stdio: 'inherit' })
  }

  const root = new protobuf.Root()
  root.resolvePath = (origin, target) => {
    if (path.isAbsolute(target)) return target
    const originDir =
      origin && origin !== 'protobufjs' ? path.dirname(origin) : null
    const candidates = []
    if (originDir) candidates.push(path.join(originDir, target))
    includeDirs.forEach((dir) => candidates.push(path.join(dir, target)))
    for (const candidate of candidates) {
      if (fs.existsSync(candidate)) return candidate
    }
    return originDir ? path.join(originDir, target) : target
  }

  await root.load(protoFiles, { keepCase: true })
  root.resolveAll()

  const messages = []
  const queue = [root]
  while (queue.length > 0) {
    const current = queue.pop()
    if (!current || !current.nestedArray) continue
    for (const nested of current.nestedArray) {
      if (nested instanceof protobuf.Type) {
        // protobuf.js does not surface synthetic map<> entry types here; they
        // are synthesized into the registry from each map field below.
        if (!nested.options?.map_entry) {
          messages.push(nested)
        }
      }
      if (nested.nestedArray) {
        queue.push(nested)
      }
    }
  }

  messages.sort((a, b) => a.fullName.localeCompare(b.fullName))

  // oneof fields work; map<> fields are encoded/decoded via their registered
  // entry type (see codec). Struct/Value/ListValue/Any still need recursion.
  // proto2 optional/required/repeated/defaults are supported; extensions and
  // groups are not - fail clearly rather than emit a broken codec.
  for (const message of messages) {
    for (const field of message.fieldsArray) {
      if (field.extend != null) {
        throw new Error(
          `Unsupported field "${cleanName(message.fullName)}.${field.name}": ` +
            'proto2 extensions are not supported (see ROADMAP.md).'
        )
      }
      if (field.type === 'group' || field.group) {
        throw new Error(
          `Unsupported field "${cleanName(message.fullName)}.${field.name}": ` +
            'proto2 groups are not supported; use a nested message instead.'
        )
      }
    }
  }

  // Validate nanopb .options for static fields. Skipped with --skipProtoc,
  // which only emits the registry (no nanopb compilation) - used by unit tests.
  // In --strict mode, require explicit options for every static field (no
  // defaults injected). Otherwise the synthesized wildcard defaults cover them.
  if (!args.skipProtoc && strict) {
    validateOptions(messages, loadOptionsKeys(includeDirs))
  } else if (!strict) {
    warnDefaultLimits(messages, loadOptionsKeys(includeDirs), defaults)
  }

  const headerIncludes = new Set([
    ...protoFiles.map((file) => `${path.basename(file, '.proto')}.pb.h`),
    ...wktImports.map((file) =>
      path.relative(wktDir, file).replace(/\.proto$/, '.pb.h')
    ),
  ])

  const lines = []
  lines.push(signedHeader('nitro_protobuf_registry.cpp', '///'))
  lines.push('#include "../cpp/ProtobufRegistry.hpp"')
  headerIncludes.forEach((header) => {
    lines.push(`#include "${header}"`)
  })
  lines.push('')
  lines.push('namespace margelo::nitro::nitroprotobuf {')
  lines.push('')

  const messageEntries = []
  for (const message of messages) {
    const fullName = message.fullName.startsWith('.')
      ? message.fullName.slice(1)
      : message.fullName
    const parts = fullName.split('.')
    const baseName = parts.join('_')
    const cBase = baseName
    const cType = cBase
    const cMsg = `${cBase}_msg`
    const cInitDefault = `${cBase}_init_default`
    const initFn = `init_default_${cBase}`
    const fieldsVar = `k_${cBase}_fields`

    lines.push(`static void ${initFn}(void* message) {`)
    lines.push(`  *static_cast<${cType}*>(message) = ${cInitDefault};`)
    lines.push('}')
    lines.push('')

    lines.push(`static const FieldInfo ${fieldsVar}[] = {`)
    for (const field of message.fieldsArray) {
      const fieldType = mapFieldType(field)
      const typeName =
        fieldType === 'Message' || fieldType === 'Enum'
          ? (field.resolvedType?.fullName?.replace(/^\./, '') ?? '')
          : ''
      const typeNameLiteral = typeName ? `"${cppString(typeName)}"` : 'nullptr'
      const isOneof = Boolean(field.partOf)
      const isMap = Boolean(field.map)
      lines.push(
        `  {"${cppString(field.name)}", ${field.id}, FieldType::${fieldType}, ` +
          `${field.repeated ? 'true' : 'false'}, ${isOneof ? 'true' : 'false'}, ` +
          `${isMap ? 'true' : 'false'}, ${typeNameLiteral}},`
      )
    }
    lines.push('};')
    lines.push('')

    messageEntries.push({
      name: fullName,
      descriptor: cMsg,
      structType: cType,
      fieldsVar,
      initFn,
      isMapEntry: Boolean(message.options?.map_entry),
    })

    // Synthesize the registration for each map<> field's nanopb entry message
    // (protoc/nanopb generate "<Msg>_<PascalField>Entry { key=1; value=2; }";
    // protobuf.js does not model it, so we emit it from keyType + value type).
    for (const field of message.fieldsArray) {
      if (!field.map) continue
      const entryStruct = `${cBase}_${pascalCase(field.name)}Entry`
      const entryInitFn = `init_default_${entryStruct}`
      const entryFieldsVar = `k_${entryStruct}_fields`
      const keyType = MAP_KEY_FIELD_TYPE[field.keyType] ?? 'String'
      const valueType = mapFieldType(field)
      const valueTypeName =
        valueType === 'Message' || valueType === 'Enum'
          ? (field.resolvedType?.fullName?.replace(/^\./, '') ?? '')
          : ''
      const valueTypeLit = valueTypeName
        ? `"${cppString(valueTypeName)}"`
        : 'nullptr'

      lines.push(`static void ${entryInitFn}(void* message) {`)
      lines.push(
        `  *static_cast<${entryStruct}*>(message) = ${entryStruct}_init_default;`
      )
      lines.push('}')
      lines.push('')
      lines.push(`static const FieldInfo ${entryFieldsVar}[] = {`)
      lines.push(
        `  {"key", 1, FieldType::${keyType}, false, false, false, nullptr},`
      )
      lines.push(
        `  {"value", 2, FieldType::${valueType}, false, false, false, ${valueTypeLit}},`
      )
      lines.push('};')
      lines.push('')
      messageEntries.push({
        name: `${fullName}.${pascalCase(field.name)}Entry`,
        descriptor: `${entryStruct}_msg`,
        structType: entryStruct,
        fieldsVar: entryFieldsVar,
        initFn: entryInitFn,
        isMapEntry: true,
      })
    }
  }

  lines.push('static const MessageInfo kMessages[] = {')
  for (const entry of messageEntries) {
    lines.push(
      `  {"${cppString(entry.name)}", &${entry.descriptor}, sizeof(${entry.structType}), ` +
        `${entry.fieldsVar}, sizeof(${entry.fieldsVar}) / sizeof(${entry.fieldsVar}[0]), ${entry.initFn}, ${entry.isMapEntry ? 'true' : 'false'}},`
    )
  }
  lines.push('};')
  lines.push('')

  lines.push('const MessageInfo* getMessageInfo(const std::string& name) {')
  lines.push('  for (const auto& message : kMessages) {')
  lines.push('    if (name == message.name) {')
  lines.push('      return &message;')
  lines.push('    }')
  lines.push('  }')
  lines.push('  return nullptr;')
  lines.push('}')
  lines.push('')

  lines.push(
    'const MessageInfo* getMessageInfo(const pb_msgdesc_s* descriptor) {'
  )
  lines.push('  for (const auto& message : kMessages) {')
  lines.push('    if (descriptor == message.descriptor) {')
  lines.push('      return &message;')
  lines.push('    }')
  lines.push('  }')
  lines.push('  return nullptr;')
  lines.push('}')
  lines.push('')

  lines.push('std::vector<std::string> getMessageNames() {')
  lines.push('  std::vector<std::string> names;')
  lines.push('  names.reserve(sizeof(kMessages) / sizeof(kMessages[0]));')
  lines.push('  for (const auto& message : kMessages) {')
  lines.push(
    '    if (message.is_map_entry) continue; // hide synthetic map entries'
  )
  lines.push('    names.emplace_back(message.name);')
  lines.push('  }')
  lines.push('  return names;')
  lines.push('}')
  lines.push('')

  lines.push(
    'const FieldInfo* findFieldByName(const MessageInfo& message, const std::string& name) {'
  )
  lines.push('  for (size_t i = 0; i < message.field_count; i++) {')
  lines.push('    const FieldInfo& field = message.fields[i];')
  lines.push('    if (name == field.name) {')
  lines.push('      return &field;')
  lines.push('    }')
  lines.push('  }')
  lines.push('  return nullptr;')
  lines.push('}')
  lines.push('')
  lines.push('} // namespace margelo::nitro::nitroprotobuf')
  lines.push('')

  const registryPath = path.join(outDir, 'nitro_protobuf_registry.cpp')
  fs.writeFileSync(registryPath, lines.join('\n'))
  console.log(`Generated registry at ${registryPath}`)

  // Typed interfaces + encode/decode facade for type-safe usage.
  const tsOut = path.resolve(cwd, args.tsOut ?? config.tsOut ?? outDir)
  fs.mkdirSync(tsOut, { recursive: true })
  const typesPath = path.join(tsOut, 'nitro-protobuf.ts')
  fs.writeFileSync(typesPath, generateTypes(messages, tsOpts))
  console.log(`Generated types at ${typesPath}`)
}

async function main() {
  const args = parseArgs(process.argv.slice(2))
  if (args.help) {
    console.log(usage())
    return
  }
  if (args._[0] === 'init') {
    runInit(process.cwd())
    return
  }

  await runGenerate(args)

  if (args.watch) {
    const cwd = process.cwd()
    const config = loadConfig(cwd)
    const protoDir = path.resolve(
      cwd,
      args.protoDir ?? config.protoDir ?? 'proto'
    )
    console.error(`[nitro-protobuf] watching ${protoDir} (Ctrl-C to stop)`)
    let timer = null
    let running = false
    const trigger = () => {
      clearTimeout(timer)
      timer = setTimeout(async () => {
        if (running) return
        running = true
        try {
          await runGenerate(args)
          console.error('[nitro-protobuf] regenerated')
        } catch (e) {
          console.error(
            '[nitro-protobuf]',
            e instanceof Error ? e.message : String(e)
          )
        } finally {
          running = false
        }
      }, 150)
    }
    fs.watch(protoDir, { recursive: true }, (_event, file) => {
      if (file && !file.endsWith('.proto')) return
      trigger()
    })
    await new Promise(() => {}) // keep the process alive until killed
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error))
  process.exit(1)
})
